pipeline {
    agent any

    stages {
        stage('Run Performance Test') {
            steps {
                script {
                    echo 'Executando testes de performance...'
                    dir('ci/load') {
                        sh 'k6_custom run --env BASE_URI=http://host.docker.internal:3333 --out xk6-prometheus-rw=http://prometheus:9090/api/v1/write ../../tests/smokeTests.js'
                    }
                }
            }
        }
    }
}