pipeline {
    agent any

    stages {
        stage('Run Load Test') {
            steps {
                script {
                    echo 'Executando testes de fumaça...'
                        sh 'k6_custom run --env BASE_URI=http://host.docker.internal:3333 tests/smokeTests.js' 
                }
            }
        }
    }
}